version: '3'

dotenv: ["metadata.env"]
silent: true

vars:
  PYTHON_VERSION:
    sh: "cat .python-version"

tasks:
  bump:
    desc: "Bump versions and update the changelog"
    cmds:
      - scripts/bump.sh

  clean:
    desc: "Clean everything"
    deps: ["clean:tests", "clean:docker"]

  clean:docker:
    desc: "Cleanup docker builder and image"
    cmds:
      - docker builder prune -a -f
      - docker image prune -a -f

  clean:tests:
    desc: "Cleanup test artifacts"
    cmds:
      - docker compose -f compose.yaml -f compose.dev.yaml down -v

  build:
    desc: "Build the docker image"
    cmds:
      - docker buildx bake build --set "*.tags=${COMFYTURE_IMAGE}:latest"

  lock:
    desc: "Lock requirements"
    cmds:
      - echo "Installing python..."
      - uv python install {{.PYTHON_VERSION}}
      - echo "Compiling requirements..."
      - |
        uv pip compile \
          --python {{.PYTHON_VERSION}} \
          --index-strategy "unsafe-best-match" \
          --format "pylock.toml" \
          --output-file "pylock.toml" requirements.in
      - echo
      - echo "👉 Compiled requirements for ComfyUI v${COMFYUI_VERSION} using Python {{.PYTHON_VERSION}}."

  preview-changelog:
    desc: "Preview next changelog"
    cmds:
      - git cliff --bump --unreleased

  tag:
    desc: "Create a new tag for this release"
    prompt: "You are about to create a new release. Continue ?"
    cmds:
      - scripts/tag.sh
      - echo "Now, push commit with tags (git push origin --tags) to create the release."

  update:
    desc: "Update ComfyUI to latest stable release"
    vars:
      LATEST_TAG:
        sh: "curl -s https://api.github.com/repos/Comfy-Org/ComfyUI/releases/latest | jq -r '.tag_name' | sed 's/^v//'"
    preconditions:
      - sh: "[ '{{.LATEST_TAG}}' != '${COMFYUI_VERSION}' ]"
        msg: "Already up-to-date (v${COMFYUI_VERSION})."
      - sh: "! git show-ref --verify --quiet refs/heads/features/comfyui-v{{.LATEST_TAG}}"
        msg: "Branch features/comfyui-v{{.LATEST_TAG}} already exists."
    cmds:
      - echo "Updating ComfyUI from v${COMFYUI_VERSION} to v{{.LATEST_TAG}}..."
      - git checkout -b "features/comfyui-v{{.LATEST_TAG}}"
      - sed -i 's/^COMFYUI_VERSION=.*/COMFYUI_VERSION={{.LATEST_TAG}}/' metadata.env
      - task: lock
      - git add metadata.env pylock.toml
      - |
        git commit -m "feat(comfy): bump to v{{.LATEST_TAG}}

        * <https://github.com/Comfy-Org/ComfyUI/releases/tag/v{{.LATEST_TAG}}>"
      - echo "Done! ComfyUI updated to v{{.LATEST_TAG}}."

  tests:
    desc: "Test to run comfyture locally"
    deps:
      - build
    cmds:
      - docker compose -f compose.yaml -f compose.dev.yaml up
